### ISSUE TITLE
Some questions from 1.3.0 to 2.0.0b4

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/VisualDL#660]
I am using `VisualDL 1.3.0` now. I mainly use the following functions:

- `LogWriter.mode`. such as `with logwriter.mode("train") as writer`
- Define before record. such as:
    ```python
    loss_scalar = writer.scalar("loss")
    loss_scalar.add_record(step, cur_loss)
    ```
- `histogram`. such as:
    ```python
    histogram1 = writer.histogram("Relation-BiLinear-W", 100)
    histogram1.add_record(step, relation_BL_w_value.flatten())
    ```
They all work well in `VisualDL 1.3.0`.

--------------------------------------------
But, when I update it to `2.0.0b4`, I found some errors respectively:

- `AttributeError: 'LogWriter' object has no attribute 'mode'`
- You don't need to define before recording. Just `writer.add_scalar()`
- There are only [three ways](https://github.com/PaddlePaddle/VisualDL/blob/develop/README.md#%E5%8F%AF%E8%A7%86%E5%8C%96%E5%8A%9F%E8%83%BD%E6%A6%82%E8%A7%88) to visualize.

**Comment by ShenYuhan** [comment]
- For convenience, we have made a lot of improvements，so the difference between the two versions is very large.
 - We are still upgrading and more components will appear soon.

**Comment by ShaneTian** [comment]
> * For convenience, we have made a lot of improvements，so the difference between the two versions is very large.
> * We are still upgrading and more components will appear soon.

OK, thank you!
In the latest version, can I use multi-level tags:
```python
writer = LogWriter(logdir="./log/")
writer.add_scalar(tag="train/acc", step=1, value=0.5678)
writer.add_scalar(tag="val/acc", step=1, value=0.1234)
```

**Comment by ShenYuhan** [comment]
You can use it like this
```
writer = LogWriter(logdir="./log/")
writer.add_scalar(tag="train/acc", step=1, value=0.5678)
# multi-level tags is allowed.
writer.add_scalar(tag="train/second/acc/acc_a", step=1, value=0.1234)
# Use writer.flush() or writer.close() to make sure all data in memory will written to disk.
writer.close()
```

**Comment by ShaneTian** [comment]
> You can use it like this
> 
> ```
> writer = LogWriter(logdir="./log/")
> writer.add_scalar(tag="train/acc", step=1, value=0.5678)
> # multi-level tags is allowed.
> writer.add_scalar(tag="train/second/acc/acc_a", step=1, value=0.1234)
> # Use writer.flush() or writer.close() to make sure all data in memory will written to disk.
> writer.close()
> ```

OK! Thank you!
